package interfaces;

/**
 * Created by Rando on 7/8/2016.
 */
public enum InterfaceConstruct {
    HEADER_FILE,FUNCTION_IGNORE,UNKNOWN, IMPORT_HEADER,CONVERSION_CONSTRUCRTOR, RENAME_FUNC, CONSTRUCTOR_IGNORE, IMPORT_SOURCE;
}
